Monologue.layout               = "layouts/blog_application" # set the layout you want to use if you want to use your main_app layout
Monologue.site_name            = "SolesOut Blog"
Monologue.site_subtitle        = "another blog about shoes"
Monologue.site_url             = "http://www.solesout.com"
Monologue.disqus_shortname     = "solesout" # register on disqus.com if you don't have one
Monologue.meta_description     = "a blog about shoes for SolesOut.com"
Monologue.twitter_username     = "solesout"
Monologue.twitter_locale       = "en" # This is the locale for twitter. "en" for english or "fr" for french. There is much more!
Monologue.facebook_like_locale = "en_US" # same, but for facebook. French is "fr_CA"
Monologue.google_plusone_locale = "en" # same for Google +
# Monologue.admin_force_ssl       = true # that can be set to false if you don't have SSL, but it is not recommended
Monologue.posts_per_page      = 3 # OPTIONAL: number of posts per page on main page. It defaults to 10 currently
Monologue.google_analytics_id  = "UA-43271759-1" # OPTIONAL: Your Google Analytics code should be here if you have one.
Monologue.sidebar              = ["latest_posts"]   # this will add the latests posts and latests tweets in the right sidebar.
Monologue.show_rss_icon        = true # will show the RSS icon (with link) in the header)
# Monologue.facebook_url         = "https://www.facebook.com/jipiboilycom" # if set, this will enable Facebook icon and link it to your Facebook page.
# Monologue.google_plus_account_url = "https://plus.google.com/115273180419164295760/posts" # if set, this will enable Google+ icon and link it to that URL.
# Monologue.linkedin_url         = "http://www.linkedin.com/in/jipiboily" # if set, will enable Linked In icon and link to this URL.
# Monologue.github_username      = "http://github.com/jipiboily"  # if set, will enable Github icon and link to this URL.
# Monologue.gauge_analytics_site_id = "your-gaug.es-id-here" # add your [Gaug.es](http://get.gaug.es/) id here to enable it.
# Monologue.facebook_logo           = 'logo.png'  # used in the open graph protocol to display an image when a post is liked
